2025-07-05 07:08:31.983369+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BOOK" not found (this database is empty); SQL statement:
SELECT * FROM book WHERE id = ? [42104-232]
2025-07-05 07:10:34.387637+09:00 database: opening /Users/jungwonpark/IdeaProjects/day-by-spring/data/bookstore
org.h2.message.DbException: Exception opening port "9093" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-232]
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.engine.Database.startServer(Database.java:679)
	at org.h2.engine.Database.<init>(Database.java:319)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at com.example.spring.traditional.TraditionalBookRepository.<init>(TraditionalBookRepository.java:16)
	at com.example.spring.traditional.TraditionalOrderService.<init>(TraditionalOrderService.java:20)
	at com.example.spring.TraditionalOrderServiceTest.testCreateOrder(TraditionalOrderServiceTest.java:28)
	at com.example.spring.TraditionalOrderServiceTest.main(TraditionalOrderServiceTest.java:43)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Exception opening port "9093" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:206)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:172)
	at org.h2.server.TcpServer.start(TcpServer.java:241)
	at org.h2.tools.Server.start(Server.java:551)
	at org.h2.engine.Database.startServer(Database.java:677)
	... 13 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.Net.bind(Net.java:554)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:636)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:391)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:278)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:171)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:202)
	... 17 more
2025-07-05 07:12:37.313773+09:00 database: opening /Users/jungwonpark/IdeaProjects/day-by-spring/data/bookstore
org.h2.message.DbException: Exception opening port "9093" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-232]
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.engine.Database.startServer(Database.java:679)
	at org.h2.engine.Database.<init>(Database.java:319)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at com.example.spring.traditional.TraditionalBookRepository.<init>(TraditionalBookRepository.java:16)
	at com.example.spring.traditional.TraditionalOrderService.<init>(TraditionalOrderService.java:20)
	at com.example.spring.traditional.TraditionalBookstoreMain.main(TraditionalBookstoreMain.java:9)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Exception opening port "9093" (port may be in use), cause: "java.net.BindException: Address already in use" [90061-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:206)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:172)
	at org.h2.server.TcpServer.start(TcpServer.java:241)
	at org.h2.tools.Server.start(Server.java:551)
	at org.h2.engine.Database.startServer(Database.java:677)
	... 12 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.Net.bind(Net.java:554)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:636)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:391)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:278)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:171)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:202)
	... 16 more
